<a href="https://colab.research.google.com/github/indra07-rm/ML-From-Scratch/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to numpy

what will be cover?

- creating arrays
- multi dimensional array
- randomly generated arrays
- element wise operations

 - comaprison operation
 - logical operations
- summarizing operations


#single dimesional array#


In [ ]:
import numpy as np

##Creating Array##

In [ ]:
var=np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

##Defining our own array##

In [ ]:
var = np.array([1, 2, 3, 4])

In [ ]:
var[2] = 5
var[-1] = 6
print(var)

[1 2 5 6]
[1 2 5 6]


##Range of number in numpy##

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

##Create array with evenly spaced number within a specific range##

In [ ]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi dimensional arrays

In [ ]:
np.zeros((5, 2)) #5 row 2 column

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#create a mud unit array of size
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#create a random array of size(3, 5) with elements using random integer

np.array(np.random.randint(5, size=(3,5)))

#create a random array of size(3,5) with elements using number of your choice

updatingA = np.array([[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10],
                      [2, 3, 6, 5, 8]])
print(updatingA)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2  3  6  5  8]]


In [ ]:
# update the element of an array with index
updatingA[1,2] = 88
print(updatingA)

[[ 1  2  3  4  5]
 [ 6  7 88  9 10]
 [ 2  3  6  5  8]]


In [ ]:
updatingA[2] = 1
updatingA[: , 2] = [2, 3, 5]
print(updatingA)

[[ 1  2  2  4  5]
 [ 6  7  3  9 10]
 [ 1  1  5  1  1]]


#Randomly generated arrays
- Numpy can createe arrays filled with random number
- To ensure the reproducibility you can use seed can be use to control the randomness that is np. random.seed()
- Everytime you can run the code with  np.random.seed(2), it will generate the exact same random numbers

#note
if you remove or changes the seed valuess, the sequence of random numbers will be changed.


In [ ]:
np.random.rand(3)

array([0.84740482, 0.67558687, 0.7126348 ])

In [ ]:
np.random.seed(3)
np.random.rand(5)


array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [ ]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [ ]:
np.random.seed(2)
np.random.randint(1, 100, 5)

array([41, 16, 73, 23, 44])

In [ ]:
np.random.randn(5,2) #normally distributed

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [ ]:
#define the numpy array
arr = np.array([[ 0.18760323, -0.32986996],
                [-1.19276461, -0.20487651],
                [-0.35882895,  0.6034716 ],
                [-1.66478853, -0.70017904],
                [ 1.15139101,  1.85733101]])

#calculate mean
mean_all = np.mean(arr) # Mean of all elements
mean_row = np.mean(arr,axis=1) # Mean of each row
mean_col = np.mean(arr, axis=0) #Mean of each column

# calculate standrad deviation
std_all = np.std(arr) # standard deviation of all elements
std_row = np.std(arr, axis=1) # standard deviation of each row
std_col = np.std(arr, axis=0) # standard deviation of each column

#print results
print("Mean of all elements:", mean_all)
print("Mean of each row:", mean_row)
print("Mean of each column:", mean_col)
print("Standard deviation of all elements:", std_all)
print("Standard deviation of each row:", std_row)
print("Standard deviation of each column:", std_col)


Mean of all elements: -0.06515107500000002
Mean of each row: [-0.07113337 -0.69882056  0.12232133 -1.18248379  1.50436101]
Mean of each column: [-0.37547757  0.24517542]
Standard deviation of all elements: 1.004804050526992
Standard deviation of each row: [0.2587366  0.49394405 0.48115027 0.48230475 0.35297   ]
Standard deviation of each column: [0.99789235 0.9115197 ]


In [ ]:
np.random.seed(42)
np.random.randint(low = 0, high = 100, size = [5, 2])

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

#Element wise operations

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [ ]:
# comparision operations
# you can perform element wise comprasion and create bolean array
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a > b

array([False, False, False, False, False])

In [ ]:
a[4] > b[0]

False

In [ ]:
#summarizing
#numpy provides functions for summarizied array of data
a

array([0, 1, 2, 3, 4])

In [ ]:
#standard deviation
a.std()


1.4142135623730951

In [ ]:
#min value of an array
a.min()


0

In [ ]:
#max value of an array
a.max()

4

In [ ]:
#sum of elements of an array
a.sum()


10

In [ ]:
#mean of array
a.mean()

2.0